# python3 -m pip install awscli # https://github.com/aws/aws-cli
# pnpm i -g serverless # https://serverless.com/framework/docs/getting-started/
# sls create -t aws-nodejs-typescript --path websocket --name 'inarea-websocket'